openapi: 3.0.0
info:
  title: API de Dicionário Distribuído
  description: API para gerir palavras e definições num sistema distribuído
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Servidor local de desenvolvimento

paths:
  /:
    put:
      summary: Criar ou atualizar uma palavra
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    key:
                      type: string
                      example: "Maçã"
                    value:
                      type: string
                      example: "Uma fruta que cresce em árvores"
      responses:
        '200':
          description: Palavra criada/atualizada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "sucesso"
        '400':
          description: Formato de requisição inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: "Formato de requisição inválido"
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: "Falha ao publicar a mensagem"
        '405': 
          $ref: '#/components/responses/MethodNotAllowed'

    get:
      summary: Obter a definição de uma palavra
      parameters:
        - name: key
          in: query
          required: true
          schema:
            type: string
          example: "Maçã"
      responses:
        '200':
          description: Resposta bem-sucedida
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      value:
                        type: string
                        example: "Uma fruta que cresce em árvores"
        '400':
          description: Parâmetro 'key' ausente
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: "Parâmetro key ausente"
        '404':
          description: Palavra não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: "Palavra não encontrada"
        '405': 
          $ref: '#/components/responses/MethodNotAllowed'

    delete:
      summary: Excluir uma palavra
      parameters:
        - name: key
          in: query
          required: true
          schema:
            type: string
          example: "Maçã"
      responses:
        '200':
          description: Palavra excluída com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "sucesso"
        '400':
          description: Parâmetro 'key' ausente
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: "Parâmetro key ausente"
        '404':
          description: Palavra não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: "Palavra não encontrada"
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: "Falha ao publicar a mensagem"
        '405': 
          $ref: '#/components/responses/MethodNotAllowed'

  /health:
    get:
      summary: Verificação de saúde do serviço
      responses:
        '200':
          description: Status do serviço
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        '503':
          description: Serviço degradado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "degradado"
        '405': 
          $ref: '#/components/responses/MethodNotAllowed'

  # Resposta para métodos não permitidos (405) - Adicionado globalmente
components:
  responses:
    MethodNotAllowed:
      description: Método não permitido
      content:
        application/json:
          schema:
            type: object
            properties:
              erro:
                type: string
                example: "Método não permitido"